### ISSUE TITLE
android:authorities="$PACKAGE_NAME.DocumentViewerPlugin.fileprovider" collides when building with other white label apps

### ISSUE THREAD

**Issue by jpike88** [sitewaerts/cordova-plugin-document-viewer#148]
Is there another way around this that doesn't depend on the package name of my product?

```
<provider
            android:name="de.sitewaerts.cordova.documentviewer.FileProvider"
            android:authorities="com.my.whitelabel.DocumentViewerPlugin.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true" >
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/documentviewer_file_paths" />
        </provider>
```

This appears in my android manifest, and even when modifying my config.xml in Cordova base path and running another prepare android, it doesn't change that value.

This means there's a collision when I'm testing multiple white label version on the simulator.

Is there a way to do this where it doesn't depend on the package name?

**Comment by regnete** [comment]
The propertry MUST be unquie and is therefore buld with your apps id as base value.
The fact that the property is not updated when you make changes in config.xml is caused by cordova. Have you tried to remove and add the plugin. May be that helps.
AIf the issue persists, you culd try to implement a hook to your cordova application which updates the value in the android manifest everytime you excute cordova prepare.

**Comment by jpike88** [comment]
Could it be made as a hash like sha256 without disrupting things?

**Comment by jpike88** [comment]
Actually yeah a hook is best, I’ll do that. Thanks
