### ISSUE TITLE
PdfRenderer instead of MuPDF

### ISSUE THREAD

**Issue by ibroom** [sitewaerts/cordova-plugin-document-viewer#20]
Great plugin!

Is there any reason why you haven't used the Android PdfRenderer library such as demonstrated at https://github.com/googlesamples/android-PdfRendererBasic instead of depending on a 3rd party app that must be installed by users on Android?

I understand this library is only available on Android 5+ but it removes an external app dependency and makes it similar to iOS.

**Comment by regnete** [comment]
Could be integrated as an optional strategy for android

**Comment by matthewcts** [comment]
this is a great plugin, and i  would like to ask if already have scheduled to integrated this new library (android pdfRenderer library) and make it more perfect.

**Comment by regnete** [comment]
We definitly won't integrate it within the next 12 months, but a contribution would be happlily accepted.

The new library renders an image for each page in the pdf. hyperlinks are not supported. so we would loose the linking feature which is not acceptable for all our use cases.

due to this reason it must be integrated as an additional/optional strategy for android which could be activated via an additonal option (https://github.com/sitewaerts/cordova-plugin-document-viewer#options).

html, css and javascript for displaying the rendered images could be reused from the windows part of this plugin (https://github.com/sitewaerts/cordova-plugin-document-viewer/tree/master/src/windows). we also have code to extract and display outline/toc there, and event pinch/zoom is supported. The available code should be splitted in a platfrom independend and a platform dependend part. After that the android specific code could be added.

So if anyone out here is able and willing to implement this feature: go ahead!
