### ISSUE TITLE
v2 -> npm -> wrong owner?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [sitewaerts/cordova-plugin-document-viewer#49]
Hallo @regnete,

I ask NPM about our problem, but they well to know a little bit more:

> I'm following up on this package issue. If you could share more about what your desired solution would be in this case, that would help determine next steps.

So, can you write more info about merge/delete wrong npm-module?

**Comment by regnete** [comment]
Thank you for taking care on this issue.

The plugin is published at npm with to different ids:

1. `cordova-plugin-document-viewer` at https://www.npmjs.com/package/cordova-plugin-document-viewer
2. `de.sitewaerts.cordova.documentviewer` at https://www.npmjs.com/package/de.sitewaerts.cordova.documentviewer

The first ID is published and maintained by me. It is based on the source at this github repo. It is up to date.

The second ID was published to npm by someone else based on a github fork. The plugin was not updated and maintained since it was first published a year ago. Even the github fork  doesn't show any activity. I think he only forked the repo to be able to publish it to npm, as we didn't publish our plugin to npm from the beginning on.

As the second ID is heavy outdated it should not be used by anybody anymore. I tried to contact the publisher but didn't get any response to my emails. He should update his github fork and republish to npm or the npm ID `de.sitewaerts.cordova.documentviewer` should be deleted/removed/redirected.

Please come back to me with any questions.

**Comment by regnete** [comment]
Just another reason to delete the old ID from npm:
The old outdated plugin is listed at cordova.apache.org, but the new one isn't.
https://cordova.apache.org/plugins/?q=pdf

**Comment by WuglyakBolgoink** [comment]
Hi @regnete, I send your message on npm-support. until yet no answer :(

**Comment by WuglyakBolgoink** [comment]
Hallo @regnete 

>  Stephanie Snopek (npm) Feb 28, 15:19 PST
>
> In this case, I would recommend going through our disputes process to request taking over the module, so you can keep it updated as needed.
https://docs.npmjs.com/policies/disputes
>
>Essentially, email the current owner with your transfer request, cc'ing npm support. Our timeline is ~4 weeks to hear back from them, and if there is no response the package is likely abandoned. In those cases of abandonment, we'd transfer the package to you so you can update it, or decide to deprecate.
>
>Let me know if you have any questions about this, I'll be here to help.
>
>Thanks so much,
>Stephanie
>Tech Support
>npm, Inc

**Comment by regnete** [comment]
Thank you. I just started the npm dispute process with an email to the owner and npm. Now we have to wait for the responses.

**Comment by regnete** [comment]
The ownership for the wrong/old npm module was passed over to me by the intial npm publisher. It's now marked as deprecated and will be removed in a few weeks.
