### ISSUE TITLE
Default PDF Viewer

### ISSUE THREAD

**Issue by bilaljawed** [sitewaerts/cordova-plugin-document-viewer#67]
I have 2/3 softwares installed of pdf, but the code fires onMissingApp and upon installing your app, everything works well, how do i fix this? without installing your viewer when i go through file manager/es explorer and open the file i can view pdf files, here's my code:
`
cordova.plugins.SitewaertsDocumentViewer.viewDocument(cordova.file.externalRootDirectory + "test.pdf", 'application/pdf', options, onShow, onClose, onMissingApp, onError);`

**Comment by bilaljawed** [comment]
Also if that's not possible, is there anyway to include the viewer in the cordova app so its not needed to be downloaded from play store again...

**Comment by regnete** [comment]
this plugins purpose is to start a dedicated external viewer app on android. you have toi specify the apps package id via the options.

if you want just to open any of the available pdf viwer apps on the device, you should not use this plugin.

it is not possible to include the viwer app into the plugin due to license restrictions in mupdf.
