### ISSUE TITLE
Android - Question about file copy, api levels and newApi()

### ISSUE THREAD

**Issue by oddcb** [sitewaerts/cordova-plugin-document-viewer#76]
Hi! I hope these are not too stupid questions (I'm not a Android dev).

In the `newApi()` method it seems that a FileProvider is only used when the device is on Nougat (Android 7) or later. Am I correct? As far as I can see the FileProvider api was added in level 22 (Android 5.1). Are there bugs or other apis preventing the use of FileProvider for earlier versions than 25?

If I'm not wrong using the FileProvider is the secure way of sharing file data with an external app. And that using the plugin in Android versions before 7 the file will be copied to the public readable external data directory? Perhaps this could be clarified under `Known issues` in the README file (currently it states that the files will be in a publicly available location in all instances).

**Comment by regnete** [comment]
This is due to backwards compatibility with the android viewer app (https://github.com/sitewaerts/android-document-viewer and https://play.google.com/store/apps/details?id=de.sitewaerts.cleverdox.viewer).

- The outdated version 1.1.2 (minSDK 15 = 4.0.3/Ice Cream Sandwich) will be still be delivered to some (probably old) devices.
  - supports old style acess via public files
- The current version 1.2.0 (minSDK 16  = 4.2/Jelly Bean) will be delivered to all other devices.
  - supports the Fileprovider API. 
  - supports old style acess via public files
  - Starting with Nougat the usage of the Fileprovider API is obligatory, the old style access via public files won't work anymore.

In order to keep maximum backwards compatibility we decided to use the FileProvider API only from SDK 24 (Nougat) upwards. Possibly we could start using it from SDK 16 upwards, but we haven't yet had the time to test it.

**Comment by regnete** [comment]
new version 0.9.5. uses FileProvider API form api level 16 upwards.
please verify if it works for you.

**Comment by oddcb** [comment]
Hi! Great. I'll try to get it verified working on a lollipop device (5.0.1) in the coming days. I don't have a device on hand myself atm.

**Comment by regnete** [comment]
any news on this issue?

**Comment by oddcb** [comment]
Hi. Have used 0.9.5 since august. No complaints from users on different versions of Android (5 upwards).

**Comment by regnete** [comment]
Great thx.
